### ISSUE TITLE
simulator or real life flag

### ISSUE THREAD

**Issue by alanswx** [evenator/CarND-Capstone#15]
In the tl_detector we need to load two different models based on the situation.  Can someone figure out if there is a variable to read, or how to tell which model we should load?

**Comment by evenator** [comment]
I'll add a flag to the launch files to load a different file based on whether we're running with `styx.launch` or `site.launch`

**Comment by evenator** [comment]
In the `tl_detector` package, there are two launch files. `launch/tl_detector.launch` is launched from the `styx.launch` file, and `launch/tl_detector_site.launch` is launched from `site.launch`. I think you should add a private parameter to `tl_detector.py` for the model file, e.g.

```
model_path = rospy.get_param("~model_path")
```

Then, set the model path differently in each of those launch files, e.g.

```xml
<?xml version="1.0"?>
<launch>
    <node pkg="tl_detector" type="tl_detector.py" name="tl_detector" output="screen" cwd="node">
        <param name="model_path" value="path/to/model"/>
    </node>
</launch>
```

**Comment by alanswx** [comment]
This is implemented in tl_training
